const List quotes = [
  "The only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle.",
  "If you can dream it, you can do it. But you have to work hard and never give up.",
  "The only thing that stands between you and your dream is the will to try and the belief that it is actually possible. So believe in yourself and never give up on your dreams.",
  "The journey of a thousand miles begins with a single step. So don't be afraid to take that first step towards your dreams.",
  "The best way to predict the future is to create it. So start planning for your future today and make your dreams a reality.",
  "The only way to fail is to give up. So never give up on your dreams, no matter how hard things get. Keep fighting for what you want and you will eventually achieve it.",
  "Never give up on something that you can't go a day without thinking about. If it's something that you truly want, then you will find a way to make it happen.",
  "The only person you are destined to become is the person you decide to be. So take control of your life and create the future that you want.",
  "The greatest glory in living lies not in never falling, but in rising every time we fall. So don't be afraid to fail. Learn from your mistakes and keep moving forward.",
  "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time. So never give up on your dreams, no matter how many times you fail. Keep trying and you will eventually succeed.",
  "It's not how much you have, but how much you enjoy that makes happiness. So focus on the positive things in your life and be grateful for what you have.",
  "Happiness is not something ready made. It comes from your own actions. So make a conscious effort to be happy and you will find that happiness comes naturally.",
  "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart. So open your heart to the beauty of the world around you and you will find true happiness.",
  "We can never obtain peace in the outer world until we make peace with ourselves. So take some time for yourself each day to relax and de-stress. When you are at peace with yourself, you will be at peace with the world around you.",
  "The mind is everything. What you think, you become. So think positive thoughts and you will attract positive things into your life.",
  "Be yourself; everyone else is already taken. So don't try to be someone you're not. Just be yourself and you will find people who love and appreciate you for who you are.",
  "The only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle.",
  "I've failed over and over and over again in my life and that is why I succeed. So don't be afraid to fail. Learn from your mistakes and keep moving forward.",
  "The difference between ordinary and extraordinary is that little extra. So go the extra mile and you will achieve great things.",
  "The only thing that stands between you and your dream is the will to try and the belief that it is actually possible. So believe in yourself and never give up on your dreams."
];
